esphome:
  name: snoopy-nose
  friendly_name: Snoopy Nose

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

mqtt:
  broker: 192.168.1.14
  port: 1883
  topic_prefix: snoopy
  keepalive: 60s
  reboot_timeout: 15min   # riavvia l'ESP se MQTT è irraggiungibile da 15min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Snoopy-Nose Fallback"
    password: !secret ap_password
  reboot_timeout: 15min   # riavvia se WiFi non torna
  power_save_mode: none   # importante! evita drop di connessione

captive_portal:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

sensor:
  - platform: bme680
    i2c_id: bus_a
    address: 0x77        # oppure 0x76, dipende dal tuo modulo
    temperature:
      name: "Temperatura"
      oversampling: 16x
    pressure:
      name: "Pressione"
      oversampling: 16x
    humidity:
      name: "Umidità"
      oversampling: 16x
    gas_resistance:
      name: "Resistenza Gas"
    heater:
      temperature: 320
      duration: 150ms
    update_interval: 60s
